import { vercelAdapter } from 'lacis/adapters';
// Generated by `lacis build` (see README). Vercel/Netlify cannot scan the
// filesystem at runtime, so routes are imported from a pre-built manifest.
import { routes, middlewares } from '../routes/_manifest.js';

// The store (src/store.ts) is backed by Postgres via Drizzle, so it persists
// fine on serverless. Just set DATABASE_URL in the platform env and run the
// migrations once (`npm run db:push`). See README "Déploiement serverless".
const handler = vercelAdapter.createHandler({
  routes,
  middlewares,
  cors: { origin: '*', allowedHeaders: ['Content-Type', 'Authorization'] },
});

export default handler;
