import { vercelAdapter } from 'lacis/adapters';
// Generated by `lacis build` (see README). Vercel/Netlify cannot scan the
// filesystem at runtime, so routes are imported from a pre-built manifest.
import { routes, middlewares } from '../routes/_manifest.js';

// NOTE: the default JSON-file store in src/store.ts will NOT persist on Vercel
// (no writable filesystem). Before deploying here, swap src/store.ts for a
// KV/Redis-backed implementation. See README "Déploiement serverless".
const handler = vercelAdapter.createHandler({
  routes,
  middlewares,
  cors: { origin: '*', allowedHeaders: ['Content-Type', 'Authorization'] },
});

export default handler;
