import { netlifyAdapter } from 'lacis/adapters';
// Generated by `lacis build`. The store (src/store.ts) is backed by Postgres via
// Drizzle, so it persists fine here — just set DATABASE_URL in the Netlify env
// (Site settings → Environment variables) and run `npm run db:push` once.
import { routes, middlewares } from '../../routes/_manifest.js';

const handler = netlifyAdapter.createHandler({
  routes,
  middlewares,
  cors: { origin: '*', allowedHeaders: ['Content-Type', 'Authorization'] },
});

export { handler };
