import { netlifyAdapter } from 'lacis/adapters';
// Generated by `lacis build`. See README "Déploiement serverless" — the default
// JSON-file store does not persist on Netlify; swap src/store.ts for KV/Redis.
import { routes, middlewares } from '../../routes/_manifest.js';

const handler = netlifyAdapter.createHandler({
  routes,
  middlewares,
  cors: { origin: '*', allowedHeaders: ['Content-Type', 'Authorization'] },
});

export { handler };
